export const TRANSLATIONS = {
    'ja': {
        'start-btn': 'ゲームスタート',
        'view-ranking-btn': 'ランキングを表示',
        'ready-text': '準備はいい？',
        'result-title': '結果発表',
        'score-label': 'スコア',
        'player-name-placeholder': '名前を入力',
        'submit-score-btn': 'ランキングに登録',
        'submitting': '送信中...',
        'ranking-title': '世界ランキング',
        'retry-btn': 'もう一度挑戦',
        'settings-title': '設定',
        'lang-label': '言語',
        'option-label': 'オプション',
        'quick-mode-label': 'スピードモード (待機なし)',
        'close-btn': '閉じる',
        'diff-label': '難易度',
        'lv1': 'Lv.1 初級',
        'lv2': 'Lv.2 初心者',
        'lv3': 'Lv.3 中級',
        'lv4': 'Lv.4 上級',
        'lv5': 'Lv.5 マニアック',
        'your-rank-label': 'あなたの順位',
        'load-error': '問題データの読み込みに失敗しました。再読み込みしてください。',
        'offline-msg': 'オフラインです。通信回復時に自動送信されます。',
        'high-score-label': '自己ベスト',
        'correct-label': '正解数',
        'correct-msg': '正解',
        'wrong-msg': '不正解',
        'question-num': '第 {0} 問',
        'overall-label': '総合',
        'category-label': 'ジャンル'
    },
    'en': {
        'start-btn': 'GAME START',
        'view-ranking-btn': 'View Ranking',
        'ready-text': 'Ready?',
        'result-title': 'Result',
        'score-label': 'Score',
        'player-name-placeholder': 'Your Name',
        'submit-score-btn': 'Submit to Ranking',
        'submitting': 'Submitting...',
        'ranking-title': 'World Ranking',
        'retry-btn': 'Retry',
        'settings-title': 'Settings',
        'lang-label': 'Language',
        'option-label': 'Option',
        'quick-mode-label': 'Quick Mode (No Delay)',
        'close-btn': 'Close',
        'diff-label': 'Difficulty',
        'lv1': 'Lv.1 Beginner',
        'lv2': 'Lv.2 Easy',
        'lv3': 'Lv.3 Normal',
        'lv4': 'Lv.4 Hard',
        'lv5': 'Lv.5 Maniac',
        'your-rank-label': 'Your Rank',
        'load-error': 'Failed to load question data. Please reload.',
        'offline-msg': 'Offline. Score will be sent when connection is restored.',
        'high-score-label': 'Personal Best',
        'correct-label': 'Correct',
        'correct-msg': 'Correct',
        'wrong-msg': 'Incorrect',
        'question-num': 'Question {0}',
        'overall-label': 'Overall',
        'category-label': 'Category'
    }
};
